version: 1

handlers:
    console:
        class: logging.StreamHandler
        stream: ext://sys.stdout

loggers:
    uvicorn:
        level: INFO
    alembic:
        level: INFO
    polymer:
        level: INFO

root:
    level: WARN
    handlers: [console]
