version: '3'

env:
  APIKEY: jHHBn91B8mUJw0hhSRsSwS8Si
  PASSWORD: As!H1NklKE5O@Ihx

tasks:
  run:
    cmds:
      - poetry run uvicorn polymer.app:app --log-config=logging.yaml --reload

  generate:
    cmds:
      - poetry run alembic revision --autogenerate {{.CLI_ARGS}}

  upgrade:
    cmds:
      - poetry run alembic upgrade head

  format:
    cmds:
      - poetry run black src
      - poetry run isort src